### ISSUE TITLE
RTCテンプレート「.travis.yaml.***」の設定が古い

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#384]
**Describe the bug**
- OpenRTP-aist 1.2.2-1 での結果で、2.0.0では確認しておりません
  - 2.0.0で同じ設定だった場合の修正を念頭にしたIssueです
- 新規RTC（例：test）を作成すると、test/.travix.yaml.test ファイルが生成されるが、この内容が現状に合っていない
- 対象としているUbuntuのバージョンが古く、利用できない環境staging.openrtm.orgを使用している
```
matrix:
  include:
    # Ubuntu14.04 + Stable OpenRTM-aist
    - os: linux
      dist: trusty
      compiler: gcc
      env: repo="http://openrtm.org/pub/Linux/ubuntu/ trusty"
    # Ubuntu12.04 + Stable OpenRTM-aist
    - os: linux
      compiler: gcc
      env: repo="http://openrtm.org/pub/Linux/ubuntu/ precise"
    # Ubuntu14.04 + Latest OpenRTM-aist
    - os: linux
      dist: trusty
      compiler: gcc
      env: repo="http://staging.openrtm.org/pub/Linux/ubuntu/ trusty"
    # Ubuntu12.04 + Latest OpenRTM-aist
    - os: linux
      compiler: gcc
      env: repo="http://staging.openrtm.org/pub/Linux/ubuntu/ precise"
```
- openrtm-aist-idlパッケージの設定が抜けている
```
efore_script:
  - echo "deb $repo main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes openrtm-aist
  - sudo apt-get install -y --force-yes openrtm-aist-dev
  - sudo apt-get install -y --force-yes openrtm-aist-example
```

**Environment**
 - OS: Ubnutn 20.04 64bits
 - OpenRTP-aist Version 1.2.2-1
